title: Sharo
email: your-email@example.com
description: Hello Marto
destination: docs
baseurl: "/Project"
url: ""
twitter_username: jekyllrb
github_username:  jekyll


plugins:
  - jekyll-feed


exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal