title: Sharo
email: your-email@example.com
description: Hello Marto
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll


plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
